homepage:
    path:     /
    defaults: { _controller: DomaineFilliatreauPresentationBundle:HomePage:index }
    
cuvees:
    path:     /cuvees
    defaults: { _controller: DomaineFilliatreauPresentationBundle:Catalogue:catalogue }

contact:
    path:     /contact
    defaults: { _controller: DomaineFilliatreauPresentationBundle:Contact:contact }
